set(EOS_DEP_GLFW_TAG 3.4)
set(EOS_DEP_SPDLOG_TAG v1.17.0)
set(EOS_DEP_GLM_TAG 1.0.3)
set(EOS_DEP_VMA_TAG v3.3.0)
set(EOS_DEP_KTX_TAG v4.4.2)
set(EOS_DEP_TRACY_TAG v0.13.1)
set(EOS_DEP_VOLK_TAG master)
set(EOS_DEP_VULKAN_UTILS_TAG main)
set(EOS_DEP_IMGUI_TAG v1.92.6)
set(EOS_DEP_FASTGLTF_TAG v0.9.0)
set(EOS_DEP_STB_TAG master)

set(EOS_DEP_SLANG_VERSION 2026.4)
set(EOS_DEP_SLANG_WINDOWS_URL "https://github.com/shader-slang/slang/releases/download/v${EOS_DEP_SLANG_VERSION}/slang-${EOS_DEP_SLANG_VERSION}-windows-x86_64.zip")
set(EOS_DEP_SLANG_LINUX_URL "https://github.com/shader-slang/slang/releases/download/v${EOS_DEP_SLANG_VERSION}/slang-${EOS_DEP_SLANG_VERSION}-linux-x86_64.tar.gz")