name: CMake Build Test

on: [push, pull_request]

jobs:
  linux-builds:
    name: Linux (${{ matrix.display_server }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        display_server: [Wayland, X11]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        if [ "${{ matrix.display_server }}" = "Wayland" ]; then
          sudo apt-get install -y libwayland-dev wayland-protocols libxkbcommon-dev
        else
          sudo apt-get install -y xorg-dev
        fi

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

  windows-build:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
