name: CMake Build Test

on: [push, pull_request]

jobs:
  linux-builds:
    name: Linux (${{ matrix.display_server }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        display_server: [Wayland, X11]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        # Add LunarG repository with proper Ubuntu version codename
        wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.275-noble.list \
        https://packages.lunarg.com/vulkan/1.3.275/lunarg-vulkan-1.3.275-noble.list
        sudo apt-get update -y
      
        # Install base dependencies
        sudo apt-get install -y build-essential cmake libvulkan-dev vulkan-validationlayers
      
        # Display server specific dependencies
        if [ "${{ matrix.display_server }}" = "Wayland" ]; then
          sudo apt-get install -y libwayland-dev wayland-protocols libxkbcommon-dev
        else
          sudo apt-get install -y xorg-dev
        fi

    - name: Set Wayland environment variable
      if: matrix.display_server == 'Wayland'
      run: echo "WAYLAND_DISPLAY=wayland-0" >> $GITHUB_ENV

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
        
  windows-build:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Vulkan SDK
      run: |
        $installerPath = "$env:RUNNER_TEMP\VulkanSDK.exe"
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.275.0/windows/VulkanSDK-1.3.275.0-Installer.exe" -OutFile $installerPath
        Start-Process -FilePath $installerPath -Args "/S" -Wait
        $vulkanVersion = "1.3.275.0"
        $vulkanPath = "C:\VulkanSDK\$vulkanVersion"
        echo "VULKAN_SDK=$vulkanPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "$vulkanPath\Bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd build
        cmake --build . --config Release

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
